# LSP----------------------------------------------------------------------
[language-server]
biome = { command = "biome", args = ["lsp-proxy"] }

[[language]]
name = "javascript"
auto-format = true
language-servers = ["typescript-language-server", "biome"]

[[language]]
name = "typescript"
auto-format = true
language-servers = ["typescript-language-server", "biome"]

[[language]]
name = "tsx"
auto-format = true
language-servers = ["typescript-language-server", "biome"]

[[language]]
name = "jsx"
auto-format = true
language-servers = ["typescript-language-server", "biome"]

[[language]]
name = "json"
language-servers = ["vscode-json-language-server", "biome"]

[[language]]
name = "rust"

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false
